CREATE TABLE `Event` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL,
	`Date`	TEXT NOT NULL,
	`Creator`	TEXT NOT NULL,
	`CreatorID`	TEXT NOT NULL
);

CREATE TABLE `Player` (
	`Name`	TEXT NOT NULL,
	`EventId`	INTEGER NOT NULL,
	`DmID`	TEXT,
	`Statut`	INTEGER NOT NULL,
	`UserID`	TEXT NOT NULL,
	`AlertID`	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY(`EventId`,`UserID`),
	FOREIGN KEY(`EventId`) REFERENCES `Event`(`ID`)
);